### ISSUE TITLE
Reqwest Error: "data did not match any variant of untagged enum ViewResponse"

### ISSUE THREAD

**Issue by LeqitDev** [sreedevk/pocketbase-sdk-rust#13]
Hi there,

first of all nice crate i really love pocketbase and are now doing things in rust so its perfect.
Now to the error i started a pocketbase server created a new collection named: "test". The i wanted to implement that in my code.
Therefore i added your crate, tokio and serde. This is my current Cargo.toml:
```toml
[dependencies]
crc64 = "2.0.0"
pocketbase-sdk = "0.0.7"
tokio = { version = "1.24.1", features = ["full"] }
serde = { version = "1.0.152", features = ["derive"] }
winconsole = "0.11.1"
```
After that i added a structure to get the data:
```rust
#[derive(Serialize, Deserialize, Debug)]
struct Test {
    id: String,
    texts: String,
    created: String,
    updated: String,
}
```
Authed as admin:
```rust
let mut client = client::Client::new("http://localhost:8090/api/").unwrap();
let auth = client.auth_via_email(
    String::from("my-email"),
    String::from("my-password"),
    UserTypes::Admin /* use UserTypes::Admin for admin Authentication */
).await;
assert!(auth.is_ok());
```
As far as now it works all perfectly fine but then i try to view anrecord with the following code:
```rust
let response = view::record::<Test>("test", "immi0lhjyil21pc", &client).await.unwrap();
```
And now i get the following error: 
`thread '<unnamed>' panicked at 'called "Result::unwrap()" on an "Err" value: reqwest::Error { kind: Decode, source: Error("data did not match any variant of untagged enum ViewResponse", line: 0, column: 0) }'`
First of all i thought its because i runned the latest version of pocketbase (v0.11.0) but after downgrading it still has the same error. And i tried `list` also but still got the same error too.

Maybe somebody has an idea why that's the case.
If you need more "original" code from me just ask.
